/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// IgnitionPayloadRendererInputsApplyConfiguration represents a declarative configuration of the IgnitionPayloadRendererInputs type for use
// with apply.
type IgnitionPayloadRendererInputsApplyConfiguration struct {
	MachineConfigServerConfigRef  *v1.LocalObjectReference `json:"machineConfigServerConfigRef,omitempty"`
	MachineConfigServerConfigHash *string                  `json:"machineConfigServerConfigHash,omitempty"`
	CloudConfigRef                *v1.LocalObjectReference `json:"cloudConfigRef,omitempty"`
	CloudConfigHash               *string                  `json:"cloudConfigHash,omitempty"`
	ManagementGlobalConfig        *string                  `json:"managementGlobalConfig,omitempty"`
}

// IgnitionPayloadRendererInputsApplyConfiguration constructs a declarative configuration of the IgnitionPayloadRendererInputs type for use with
// apply.
func IgnitionPayloadRendererInputs() *IgnitionPayloadRendererInputsApplyConfiguration {
	return &IgnitionPayloadRendererInputsApplyConfiguration{}
}

// WithMachineConfigServerConfigRef sets the MachineConfigServerConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineConfigServerConfigRef field is set to the value of the last call.
func (b *IgnitionPayloadRendererInputsApplyConfiguration) WithMachineConfigServerConfigRef(value v1.LocalObjectReference) *IgnitionPayloadRendererInputsApplyConfiguration {
	b.MachineConfigServerConfigRef = &value
	return b
}

// WithMachineConfigServerConfigHash sets the MachineConfigServerConfigHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineConfigServerConfigHash field is set to the value of the last call.
func (b *IgnitionPayloadRendererInputsApplyConfiguration) WithMachineConfigServerConfigHash(value string) *IgnitionPayloadRendererInputsApplyConfiguration {
	b.MachineConfigServerConfigHash = &value
	return b
}

// WithCloudConfigRef sets the CloudConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudConfigRef field is set to the value of the last call.
func (b *IgnitionPayloadRendererInputsApplyConfiguration) WithCloudConfigRef(value v1.LocalObjectReference) *IgnitionPayloadRendererInputsApplyConfiguration {
	b.CloudConfigRef = &value
	return b
}

// WithCloudConfigHash sets the CloudConfigHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudConfigHash field is set to the value of the last call.
func (b *IgnitionPayloadRendererInputsApplyConfiguration) WithCloudConfigHash(value string) *IgnitionPayloadRendererInputsApplyConfiguration {
	b.CloudConfigHash = &value
	return b
}

// WithManagementGlobalConfig sets the ManagementGlobalConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementGlobalConfig field is set to the value of the last call.
func (b *IgnitionPayloadRendererInputsApplyConfiguration) WithManagementGlobalConfig(value string) *IgnitionPayloadRendererInputsApplyConfiguration {
	b.ManagementGlobalConfig = &value
	return b
}
