/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	hypershiftv1alpha1 "github.com/openshift/hypershift/api/hypershift/v1alpha1"
	applyconfigurationhypershiftv1alpha1 "github.com/openshift/hypershift/client/applyconfiguration/hypershift/v1alpha1"
	scheme "github.com/openshift/hypershift/client/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IgnitionPayloadsGetter has a method to return a IgnitionPayloadInterface.
// A group's client should implement this interface.
type IgnitionPayloadsGetter interface {
	IgnitionPayloads(namespace string) IgnitionPayloadInterface
}

// IgnitionPayloadInterface has methods to work with IgnitionPayload resources.
type IgnitionPayloadInterface interface {
	Create(ctx context.Context, ignitionPayload *hypershiftv1alpha1.IgnitionPayload, opts v1.CreateOptions) (*hypershiftv1alpha1.IgnitionPayload, error)
	Update(ctx context.Context, ignitionPayload *hypershiftv1alpha1.IgnitionPayload, opts v1.UpdateOptions) (*hypershiftv1alpha1.IgnitionPayload, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ignitionPayload *hypershiftv1alpha1.IgnitionPayload, opts v1.UpdateOptions) (*hypershiftv1alpha1.IgnitionPayload, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hypershiftv1alpha1.IgnitionPayload, error)
	List(ctx context.Context, opts v1.ListOptions) (*hypershiftv1alpha1.IgnitionPayloadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hypershiftv1alpha1.IgnitionPayload, err error)
	Apply(ctx context.Context, ignitionPayload *applyconfigurationhypershiftv1alpha1.IgnitionPayloadApplyConfiguration, opts v1.ApplyOptions) (result *hypershiftv1alpha1.IgnitionPayload, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, ignitionPayload *applyconfigurationhypershiftv1alpha1.IgnitionPayloadApplyConfiguration, opts v1.ApplyOptions) (result *hypershiftv1alpha1.IgnitionPayload, err error)
	IgnitionPayloadExpansion
}

// ignitionPayloads implements IgnitionPayloadInterface
type ignitionPayloads struct {
	*gentype.ClientWithListAndApply[*hypershiftv1alpha1.IgnitionPayload, *hypershiftv1alpha1.IgnitionPayloadList, *applyconfigurationhypershiftv1alpha1.IgnitionPayloadApplyConfiguration]
}

// newIgnitionPayloads returns a IgnitionPayloads
func newIgnitionPayloads(c *HypershiftV1alpha1Client, namespace string) *ignitionPayloads {
	return &ignitionPayloads{
		gentype.NewClientWithListAndApply[*hypershiftv1alpha1.IgnitionPayload, *hypershiftv1alpha1.IgnitionPayloadList, *applyconfigurationhypershiftv1alpha1.IgnitionPayloadApplyConfiguration](
			"ignitionpayloads",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *hypershiftv1alpha1.IgnitionPayload { return &hypershiftv1alpha1.IgnitionPayload{} },
			func() *hypershiftv1alpha1.IgnitionPayloadList { return &hypershiftv1alpha1.IgnitionPayloadList{} },
		),
	}
}
