//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionPayload) DeepCopyInto(out *IgnitionPayload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionPayload.
func (in *IgnitionPayload) DeepCopy() *IgnitionPayload {
	if in == nil {
		return nil
	}
	out := new(IgnitionPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IgnitionPayload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionPayloadList) DeepCopyInto(out *IgnitionPayloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IgnitionPayload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionPayloadList.
func (in *IgnitionPayloadList) DeepCopy() *IgnitionPayloadList {
	if in == nil {
		return nil
	}
	out := new(IgnitionPayloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IgnitionPayloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionPayloadRendererInputs) DeepCopyInto(out *IgnitionPayloadRendererInputs) {
	*out = *in
	out.MachineConfigServerConfig = in.MachineConfigServerConfig
	if in.CloudConfig != nil {
		in, out := &in.CloudConfig, &out.CloudConfig
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionPayloadRendererInputs.
func (in *IgnitionPayloadRendererInputs) DeepCopy() *IgnitionPayloadRendererInputs {
	if in == nil {
		return nil
	}
	out := new(IgnitionPayloadRendererInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionPayloadSpec) DeepCopyInto(out *IgnitionPayloadSpec) {
	*out = *in
	if in.AdditionalTrustBundle != nil {
		in, out := &in.AdditionalTrustBundle, &out.AdditionalTrustBundle
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.MgmtConfig != nil {
		in, out := &in.MgmtConfig, &out.MgmtConfig
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.RolloutConfig != nil {
		in, out := &in.RolloutConfig, &out.RolloutConfig
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.RetiredGeneration != nil {
		in, out := &in.RetiredGeneration, &out.RetiredGeneration
		*out = new(int64)
		**out = **in
	}
	in.RendererInputs.DeepCopyInto(&out.RendererInputs)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionPayloadSpec.
func (in *IgnitionPayloadSpec) DeepCopy() *IgnitionPayloadSpec {
	if in == nil {
		return nil
	}
	out := new(IgnitionPayloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionPayloadStatus) DeepCopyInto(out *IgnitionPayloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Current.DeepCopyInto(&out.Current)
	in.Previous.DeepCopyInto(&out.Previous)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionPayloadStatus.
func (in *IgnitionPayloadStatus) DeepCopy() *IgnitionPayloadStatus {
	if in == nil {
		return nil
	}
	out := new(IgnitionPayloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PayloadReference) DeepCopyInto(out *PayloadReference) {
	*out = *in
	if in.Generation != nil {
		in, out := &in.Generation, &out.Generation
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PayloadReference.
func (in *PayloadReference) DeepCopy() *PayloadReference {
	if in == nil {
		return nil
	}
	out := new(PayloadReference)
	in.DeepCopyInto(out)
	return out
}
